# Generated by Django 4.1.7 on 2023-03-30 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_category_title_alter_tag_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='photos/default_user_avatar.png', help_text='Only .png format. Less than 0.5mb.', upload_to='photos/avatars/%Y/%m/%d/', verbose_name='User avatar')),
                ('bio', models.TextField(blank=True, max_length=200, verbose_name='information')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('karma', models.BigIntegerField(default=0, verbose_name='Total karma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
