# Generated by Django 4.1.7 on 2023-04-04 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_userprofile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DELETED', 'Deleted')], default='APPROVED', max_length=15, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250, verbose_name='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('status', models.CharField(choices=[('VISIBLE', 'Visible'), ('INVISIBLE', 'Invisible'), ('DELETED', 'Deleted')], default='VISIBLE', max_length=15, verbose_name='Status')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('count_of_likes', models.PositiveIntegerField(default=0, verbose_name='Count of likes')),
                ('count_of_dislikes', models.PositiveIntegerField(default=0, verbose_name='Count of dislikes')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='news.comment', verbose_name='Parent comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.post')),
                ('user_submitter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_user_submitter', to=settings.AUTH_USER_MODEL, verbose_name='User submitter')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
