# Generated by Django 4.1.7 on 2023-04-18 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_post_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_news', models.CharField(max_length=100, verbose_name='News type')),
            ],
            options={
                'verbose_name': 'News Type',
                'verbose_name_plural': 'News Types',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Is user subscribed?')),
                ('email', models.EmailField(max_length=150, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('choices', models.ManyToManyField(blank=True, to='news.newstype', verbose_name='News choice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_newsletter_subscriber', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
