# Generated by Django 4.1.7 on 2023-04-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newstype_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='information'),
        ),
    ]
