# Generated by Django 4.1.7 on 2023-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_actiontrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontrack',
            name='action',
            field=models.CharField(choices=[('View', 'View'), ('Redirect', 'Go To'), ('Get object', 'Get Object'), ('Submit post', 'Submit Post'), ('View post', 'Post View'), ('Post rating plus 1', 'Post Rating Plus'), ('Post rating minus 1', 'Post Rating Minus'), ('Comment rating liked', 'Comment Rating Plus'), ('Comment rating disliked', 'Comment Rating Minus'), ('Create new child comment', 'Create New Child Comment')], max_length=100, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='actiontrack',
            name='action_reason',
            field=models.CharField(choices=[('Object not exist', 'Object Not Exist'), ("Haven't permissions", 'Havent Permissions'), ('Only owner can view (Object status) status', 'Object Status Only Owner'), ('Form invalid', 'Form Invalid'), ('Object submit spam', 'Object Submit Spam'), ('Coupon views change unsuccessfully. Already viewed', 'Post Already Viewed'), ('Coupon rating change unsuccessfully. Already changed', 'Post Rating Already Changed'), ('Comment rating change unsuccessfully. Already changed', 'Comment Rating Already Changed')], max_length=100, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='actiontrack',
            name='page',
            field=models.CharField(choices=[('Main(Index) page', 'Page Index'), ('Community page', 'Page Community'), ('Post profile(with comments) page', 'Post Profile'), ('Post submit page', 'Post Submit'), ('User profile page', 'User Profile'), ('User profile summary page', 'User Profile Summary'), ('User profile publications page', 'User Profile Publications'), ('User profile platform page', 'User Profile Platform'), ('Login page', 'Login'), ('Registration page', 'Registration'), ('Password reset view', 'Reset Password'), ('Password change view', 'Change Password'), ('Post API', 'Api Post'), ('Comment API rating', 'Api Comment Rating'), ('Post status -> DELETED', 'Post Deleted'), ('Favorite API', 'Api Favorite'), ('Like/Dislike API', 'Api Like Dislike'), ('Karma', 'Karma')], max_length=100, verbose_name='Page'),
        ),
    ]
