# Generated by Django 4.1.7 on 2023-05-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/categories/%Y/%m/%d/', verbose_name='Photo for category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default_blog_image.jpg', upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
