# Generated by Django 4.1.7 on 2023-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_userprofile_monthly_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontrack',
            name='action',
            field=models.CharField(choices=[('View', 'View'), ('Redirect', 'Go To'), ('Get object', 'Get Object'), ('Submit post', 'Submit Post'), ('View post', 'Post View'), ('Post rating plus 1', 'Post Rating Plus'), ('Post rating minus 1', 'Post Rating Minus'), ('Everyday bonus', 'Everyday Karma Given'), ('Comment rating liked', 'Comment Rating Plus'), ('Comment rating disliked', 'Comment Rating Minus'), ('Create new child comment', 'Create New Child Comment')], max_length=100, verbose_name='Action'),
        ),
    ]
