version: "3.9"

services:
  redis:
    image: redis:6
    container_name: composer_redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    image: djangoblog:latest
    build:
      context: .
    working_dir: /code
    command: bash -c "ls -l && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis


#  celery:
#    image: djangoblog:latest
#    working_dir: /code
#    command: celery -A project worker -l info --pool=solo
##    volumes:
##      - .:/code
#    env_file:
#      - .env
#    environment:
#      - DB_NAME=blog
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#      - DB_HOST=db
#      - REDIS_HOST=redis
#      - DJANGO_SETTINGS_MODULE=project.settings.dev_local
#    depends_on:
#      - db
#      - redis