run:
	./manage.py runserver

run-front:
	npm start

migrate:
	./manage.py migrate

freeze:
	pip freeze > requirements.txt

requirements:
	pip install -r requirements.txt

static:
	./manage.py collectstatic